config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from pilotage.api import urls as api_urls
from pilotage.dashboards import urls as dashboards_urls
from pilotage.pilotage import urls as pilotage_urls
from pilotage.surveys import urls as surveys_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(api_urls)),
    path("survey/", include(surveys_urls)),
    path("", include(pilotage_urls)),
    path("", include(dashboards_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pilotage/api/urls.py
from django.urls import path

from pilotage.api import views


app_name = "api"
urlpatterns = [
    path("dataset/<slug:name>", views.dataset, name="dataset"),
]

pilotage/dashboards/urls.py
from django.urls import path

from pilotage.dashboards import views


app_name = "dashboards"
urlpatterns = [
    path(
        "tableaux-de-bord/",
        views.tableaux_de_bord_publics,
        name="tableaux_de_bord_publics",
    ),
    path(
        "tableaux-de-bord/<slug:slug>/",
        views.tableau_de_bord_public,
        name="tableau_de_bord_public",
    ),
]

pilotage/pilotage/urls.py
from django.urls import include, path

from pilotage.pilotage import views


app_name = "pilotage"
urlpatterns = [
    path("", views.home, name="home"),
    path("dashboards/", include("pilotage.dashboards.urls")),
    path("stats/", views.stats, name="statistiques"),
    path("accessibilite/", views.accessibilite, name="accessibilite"),
    path("mentions-legales/", views.mentions_legales, name="mentions_legales"),
    path(
        "politique-de-confidentialite/",
        views.politique_de_confidentialite,
        name="politique_de_confidentialite",
    ),
    path(
        "inscription-lettre-information/",
        views.inscription_lettre_information,
        name="inscription_lettre_information",
    ),
    path(
        "tableaux-de-bord-prives/",
        views.tableaux_de_bord_prives,
        name="tableaux_de_bord_prives",
    ),
]

pilotage/surveys/urls.py
from django.urls import path

from pilotage.surveys import views


app_name = "surveys"
urlpatterns = [
    path("<slug:survey_name>/", views.start, name="start"),
    path("<slug:survey_name>/<uuid:answer_uid>/<str:step>", views.tunnel, name="tunnel"),
]

pilotage/dashboards/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name = "catégorie"
        verbose_name_plural = "catégories"

    title = models.fields.CharField(verbose_name="titre", validators=[MaxLengthValidator(100)])
    display_order = models.fields.PositiveSmallIntegerField(verbose_name="ordre d'affichage", blank=True, default=0)

    def __str__(self):
        return f"{self.title}"


class Dashboard(models.Model):
    class Meta:
        verbose_name = "tableau de bord"
        verbose_name_plural = "tableaux de bord"

    title = models.fields.CharField(verbose_name="titre", validators=[MaxLengthValidator(150)])
    baseline = models.fields.CharField(validators=[MaxLengthValidator(250)])
    slug = models.fields.SlugField(unique=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.DO_NOTHING,
        verbose_name="catégorie",
    )
    metabase_db_id = models.fields.IntegerField(verbose_name="metabase ID")
    embed_url = models.fields.URLField(
        verbose_name="embed URL",
        help_text="Si vous souhaitez ajouter une url d'iframe à la place d'un 'Metabase ID', "
        "vous devez de mettre 0 dans le 'Metabase ID' et ajouter une url ci-dessus",
        null=True,
        blank=True,
    )
    description = models.fields.TextField(null=True, blank=True)
    tally_popup_id = models.fields.CharField(
        verbose_name="tally popup ID", null=True, blank=True, validators=[MaxLengthValidator(10)]
    )
    tally_embed_id = models.fields.CharField(
        verbose_name="tally embed ID", null=True, blank=True, validators=[MaxLengthValidator(10)]
    )
    active = models.fields.BooleanField(verbose_name="actif", default=True)
    new = models.fields.BooleanField(verbose_name="nouveau", default=False)

    def __str__(self):
        return f"{self.title}"

pilotage/users/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models


class UserGroup(AbstractUser):
    EDITOR = "EDITOR"
    SUBSCRIBER = "SUBSCRIBER"

    ROLE_CHOICES = (
        (EDITOR, "Éditeur"),
        (SUBSCRIBER, "Abonné"),
    )
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name="rôle")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.role == self.EDITOR:
            group = Group.objects.get(name="editors")
            group.user_set.add(self)
        elif self.role == self.SUBSCRIBER:
            group = Group.objects.get(name="subscribers")
            group.user_set.add(self)

pilotage/itoutils/forms.py
import string


class EmptyPlaceholderFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["placeholder"] = ""


class LetteredLabelFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for idx, field in enumerate(self.fields.values()):
            field.label = f"{string.ascii_lowercase[idx]}. {field.label}"

pilotage/api/views.py
import copy

from django.conf import settings
from django.db.models.enums import TextChoices
from django.http import (
    JsonResponse,
)

from pilotage.itoutils import metabase
from pilotage.itoutils.departments import DEPARTMENTS


class DataSetName(TextChoices):
    # API V0
    DI_SERVICES_V0 = "di_services", "data·inclusion - Services"
    DI_STRUCTURES_V0 = "di_structures", "data·inclusion - Structures"
    # API V1
    DI_SERVICES_V1 = "di_services_v1", "data·inclusion - Services"
    DI_STRUCTURES_V1 = "di_structures_v1", "data·inclusion - Structures"


QUERIES = {
    # API V0
    DataSetName.DI_SERVICES_V0: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2052,
            "fields": [
                ["field", 59639, {"base-type": "type/Text"}],  # ID
                ["field", 59644, {"base-type": "type/Text"}],  # Structure ID
                ["field", 59647, {"base-type": "type/Text"}],  # Source
                ["field", 59614, {"base-type": "type/Text"}],  # Nom
                ["field", 59643, {"base-type": "type/*"}],  # Thematiques
                ["field", 59627, {"base-type": "type/*"}],  # Frais
                ["field", 59636, {"base-type": "type/*"}],  # Profils
                ["field", 59649, {"base-type": "type/Text"}],  # Commune
                ["field", 59623, {"base-type": "type/Text"}],  # Code Postal
                ["field", 59654, {"base-type": "type/Text"}],  # Code Insee
                ["field", 59615, {"base-type": "type/Text"}],  # Adresse
                ["field", 59629, {"base-type": "type/Float"}],  # Longitude
                ["field", 59651, {"base-type": "type/Float"}],  # Latitude
                ["field", 59624, {"base-type": "type/*"}],  # Modes Accueil
            ],
            "filter": [
                "starts-with",
                ["field", 59654, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
    DataSetName.DI_STRUCTURES_V0: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2051,
            "fields": [
                ["field", 59591, {"base-type": "type/Text"}],  # ID
                ["field", 59600, {"base-type": "type/Text"}],  # Nom
                ["field", 59608, {"base-type": "type/Text"}],  # Commune
                ["field", 59606, {"base-type": "type/Text"}],  # Code Postal
                ["field", 59588, {"base-type": "type/Text"}],  # Code Insee
                ["field", 59605, {"base-type": "type/Text"}],  # Adresse
                ["field", 59594, {"base-type": "type/Float"}],  # Longitude
                ["field", 59599, {"base-type": "type/Float"}],  # Latitude
                ["field", 59590, {"base-type": "type/Text"}],  # Typologie
            ],
            "filter": [
                "starts-with",
                ["field", 59588, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
    # API V1
    DataSetName.DI_SERVICES_V1: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2169,
            "fields": [
                ["field", 62677, {"base-type": "type/Text"}],  # Source
                ["field", 62706, {"base-type": "type/Text"}],  # Structure ID
                ["field", 62694, {"base-type": "type/Text"}],  # ID
                ["field", 62685, {"base-type": "type/Text"}],  # Nom
                ["field", 62704, {"base-type": "type/*"}],  # Thematiques
                ["field", 62692, {"base-type": "type/Text"}],  # Frais
                ["field", 62710, {"base-type": "type/*"}],  # Publics
                ["field", 62700, {"base-type": "type/Text"}],  # Commune
                ["field", 62696, {"base-type": "type/Text"}],  # Code Postal
                ["field", 62686, {"base-type": "type/Text"}],  # Code Insee
                ["field", 62683, {"base-type": "type/Text"}],  # Adresse
                ["field", 62681, {"base-type": "type/Float"}],  # Longitude
                ["field", 62699, {"base-type": "type/Float"}],  # Latitude
                ["field", 62682, {"base-type": "type/*"}],  # Modes accueil
            ],
            "filter": [
                "starts-with",
                ["field", 62686, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
    DataSetName.DI_STRUCTURES_V1: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2170,
            "fields": [
                ["field", 62728, {"base-type": "type/Text"}],  # Source
                ["field", 62727, {"base-type": "type/Text"}],  # ID
                ["field", 62721, {"base-type": "type/Text"}],  # Nom
                ["field", 62716, {"base-type": "type/Text"}],  # Commune
                ["field", 62730, {"base-type": "type/Text"}],  # Code Postal
                ["field", 62719, {"base-type": "type/Text"}],  # Code Insee
                ["field", 62718, {"base-type": "type/Text"}],  # Adresse
                ["field", 62711, {"base-type": "type/Float"}],  # Longitude
                ["field", 62715, {"base-type": "type/Float"}],  # Latitude
                ["field", 62717, {"base-type": "type/*"}],  # Reseaux Porteurs
            ],
            "filter": [
                "starts-with",
                ["field", 62719, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
}


def dataset(request, name):
    if name not in DataSetName:
        return JsonResponse({"error": "Dataset doesn't exists"}, status=404)

    # TODO: Use a query-builder like function to avoid a global and copying the query
    query = copy.deepcopy(QUERIES[DataSetName(name)])
    if department := request.GET.get("department"):
        if department not in DEPARTMENTS:
            return JsonResponse({"error": "Department doesn't exists"}, status=400)
        query["query"]["filter"][2] = department
    else:
        return JsonResponse({"error": "Department is a required query parameter"}, status=400)

    return JsonResponse(
        metabase.Client(settings.METABASE_BASE_URL).fetch_dataset_results(query),
        safe=False,  # Metabase return a list
    )

pilotage/dashboards/views.py
from django.shortcuts import get_object_or_404, render

from pilotage.dashboards.models import Dashboard


def tableaux_de_bord_publics(request):
    dashboards = (
        Dashboard.objects.filter(active=True)
        .select_related("category")
        .order_by("category__display_order", "-category__pk", "-pk")
    )
    return render(
        request,
        "dashboards/tableaux_de_bord_publics.html",
        context={"dashboards": dashboards},
    )


def tableau_de_bord_public(request, slug):
    dashboard = get_object_or_404(Dashboard, slug=slug)
    return render(
        request,
        "dashboards/tableau_de_bord_public.html",
        context={
            "dashboard": dashboard,
            "slug": slug,
            # Parameters for "partials/footer-scripts.html"
            "hasIframeResizer": not dashboard.embed_url,
            "hasIframeResizerFromOther": dashboard.embed_url,
            "hasTallyEmbed": dashboard.tally_embed_id,
            "hasTallyPopup": dashboard.tally_popup_id,
        },
    )

pilotage/pilotage/views.py
from django.shortcuts import render


def home(request):
    return render(request, "pilotage/home.html")


def stats(request):
    return render(request, "pilotage/statistiques.html")


def accessibilite(request):
    return render(request, "pilotage/accessibilite.html")


def politique_de_confidentialite(request):
    return render(request, "pilotage/politique_de_confidentialite.html")


def inscription_lettre_information(request):
    return render(request, "pilotage/inscription_lettre_information.html")


def mentions_legales(request):
    return render(request, "pilotage/mentions_legales.html")


def tableaux_de_bord_prives(request):
    return render(request, "pilotage/tableaux_de_bord_prives.html")

pilotage/users/views.py
from django.shortcuts import render

# Create your views here.

pilotage/templates/dashboards/tableau_de_bord_public.html
{% extends "layouts/base.html" %}
{% load static %}
{% load i18n %}
{% load markdown_extras %}
{% load metabase_extras %}

{% block title %}{{ dashboard.title }} - Tableaux de bord publics - {{ block.super }}{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="c-breadcrumb" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'pilotage:home' %}">Accueil</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'dashboards:tableaux_de_bord_publics' %}">Statistiques publiques</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{ dashboard.title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    <section class="s-title-01">
        <div class="s-title-01__container container">
            <div class="s-title-01__row row">
                <div class="s-title-01__col col-12 col-lg-12">
                    <h1>
                        {{ dashboard.title }}
                        {% if dashboard.new %}<span class="badge badge-base rounded-pill bg-important">Nouveau</span>{% endif %}
                    </h1>
                    {% if dashboard.description %}<div>{{ dashboard.description | markdown | safe }}</div>{% endif %}
                </div>
            </div>
        </div>
    </section>

    {% if dashboard.embed_url %}
        <!-- Quick win crassou aussi pour permettre d'afficher des TBs provenant d'ailleurs que de metabase -->
        <section class="s-embed m-0">
            <div class="s-embed__container container">
                <div class="s-embed__row row">
                    <div class="col-12">
                        <iframe src="{{ dashboard.embed_url }}" title="{{ dashboard.baseline }}" id="iframeFromOther" allowtransparency></iframe>
                    </div>
                </div>
            </div>
        </section>
    {% else %}
        <section class="s-embed m-0">
            <div class="s-embed__container container">
                <div class="s-embed__row row">
                    <div class="col-12">
                        <iframe src="{{ dashboard.metabase_db_id | iframeurl }}" title="{{ dashboard.baseline }}" id="iframeMetabase" allowtransparency></iframe>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}

    {% if dashboard.tally_embed_id %}
        <section class="s-embed s-embed--tally">
            <div class="s-embed__container container">
                <div class="s-embed__row row">
                    <div class="s-embed__col col-12">
                        <iframe data-tally-src="//tally.so/embed/{{ dashboard.tally_embed_id }}?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1"
                                loading="lazy"
                                width="100%"
                                height="189"
                                title="Aidez-nous à améliorer votre outil !"></iframe>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}
{% endblock %}

pilotage/templates/dashboards/tableaux_de_bord_publics.html
{% extends "layouts/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}Statistiques publiques - {{ block.super }}{% endblock %}

{% block body_class %}l-tableaux-de-bord{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="c-breadcrumb" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'pilotage:home' %}">Accueil</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Statistiques publiques</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    <section class="s-title-01">
        <div class="s-title-01__container container">
            <div class="s-title-01__row row">
                <div class="s-title-01__col col-12 col-xl-11">
                    <h1>Statistiques publiques</h1>
                    <p>Le pilotage de l'inclusion vise à résoudre les problématiques métier des professionnels sur le terrain et de leurs partenaires par la donnée. Cette approche se matérialise principalement à travers des tableaux de bord comprenant des données actualisées en temps réel. Ces outils, qu'ils soient stratégiques, opérationnels ou de suivi, s'adressent à tous les acteurs de l'inclusion. Les informations peuvent être affinées pour un territoire spécifique, tel qu'un bassin d'emploi, un type d'organisation comme une entreprise d'insertion ou un conseil départemental, et sur une période donnée. Grâce à ces connaissances, les utilisateurs peuvent ainsi suivre leurs progrès, se comparer, améliorer leurs échanges avec les financeurs et les partenaires, et enrichir leurs plans d'action et feuilles de route.</p>
                    <p class="h4">
                        Plaquette présentant l’ensemble des tableaux de bord développés par le Pilotage de l’inclusion
                        <a href="https://www.canva.com/design/DAF_5XyJqRk/fV5Rpv649EU5P0GJCo0VJQ/view?utm_content=DAF_5XyJqRk&utm_campaign=designshare&utm_medium=link&utm_source=editor"
                           target="_blank"
                           class="has-external-link text-nowrap"
                           aria-label="Plaquette présentant l’ensemble des tableaux de bord">disponible ici</a>.
                    </p>
                </div>
            </div>
        </div>
    </section>

    {% regroup dashboards by category as categorized_dashboards %}
    {% for category in categorized_dashboards %}
        <section class="s-tableaux">
            <div class="s-tableaux__container container">
                <div class="s-tableaux__row row mb-3">
                    <div class="col-12">
                        <h2 class="text-secondary">{{ category.grouper.title }}</h2>
                    </div>
                </div>
                <div class="s-tableaux__row row">
                    <div class="s-tableaux__col s-tableaux__col--grid col-12">
                        {% for dashboard in category.list %}
                            <div class="d-flex flex-column justify-content-between position-relative">
                                <div>
                                    <h3>
                                        {{ dashboard.title }}
                                        {% if dashboard.new %}<span class="badge badge-sm rounded-pill bg-important">Nouveau</span>{% endif %}
                                    </h3>
                                    <p>{{ dashboard.baseline }}</p>
                                </div>
                                <p class="s-tableaux__col__cta">
                                    <a href="{% url 'dashboards:tableau_de_bord_public' dashboard.slug %}" rel="noopener" class="btn btn-outline-primary stretched-link">Voir le tableau de bord</a>
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    {% endfor %}
{% endblock %}