config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from pilotage.api import urls as api_urls
from pilotage.dashboards import urls as dashboards_urls
from pilotage.pilotage import urls as pilotage_urls
from pilotage.surveys import urls as surveys_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(api_urls)),
    path("survey/", include(surveys_urls)),
    path("", include(pilotage_urls)),
    path("", include(dashboards_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pilotage/api/urls.py
from django.urls import path

from pilotage.api import views


app_name = "api"
urlpatterns = [
    path("dataset/<slug:name>", views.dataset, name="dataset"),
]

pilotage/dashboards/urls.py
from django.urls import path

from pilotage.dashboards import views


app_name = "dashboards"
urlpatterns = [
    path(
        "tableaux-de-bord/",
        views.tableaux_de_bord_publics,
        name="tableaux_de_bord_publics",
    ),
    path(
        "tableaux-de-bord/<slug:slug>/",
        views.tableau_de_bord_public,
        name="tableau_de_bord_public",
    ),
]

pilotage/pilotage/urls.py
from django.urls import include, path

from pilotage.pilotage import views


app_name = "pilotage"
urlpatterns = [
    path("", views.home, name="home"),
    path("dashboards/", include("pilotage.dashboards.urls")),
    path("stats/", views.stats, name="statistiques"),
    path("accessibilite/", views.accessibilite, name="accessibilite"),
    path("mentions-legales/", views.mentions_legales, name="mentions_legales"),
    path(
        "politique-de-confidentialite/",
        views.politique_de_confidentialite,
        name="politique_de_confidentialite",
    ),
    path(
        "inscription-lettre-information/",
        views.inscription_lettre_information,
        name="inscription_lettre_information",
    ),
    path(
        "tableaux-de-bord-prives/",
        views.tableaux_de_bord_prives,
        name="tableaux_de_bord_prives",
    ),
]

pilotage/surveys/urls.py
from django.urls import path

from pilotage.surveys import views


app_name = "surveys"
urlpatterns = [
    path("<slug:survey_name>/", views.start, name="start"),
    path("<slug:survey_name>/<uuid:answer_uid>/<str:step>", views.tunnel, name="tunnel"),
]

pilotage/dashboards/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name = "catégorie"
        verbose_name_plural = "catégories"

    title = models.fields.CharField(verbose_name="titre", validators=[MaxLengthValidator(100)])
    display_order = models.fields.PositiveSmallIntegerField(verbose_name="ordre d'affichage", blank=True, default=0)

    def __str__(self):
        return f"{self.title}"


class Dashboard(models.Model):
    class Meta:
        verbose_name = "tableau de bord"
        verbose_name_plural = "tableaux de bord"

    title = models.fields.CharField(verbose_name="titre", validators=[MaxLengthValidator(150)])
    baseline = models.fields.CharField(validators=[MaxLengthValidator(250)])
    slug = models.fields.SlugField(unique=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.DO_NOTHING,
        verbose_name="catégorie",
    )
    metabase_db_id = models.fields.IntegerField(verbose_name="metabase ID")
    embed_url = models.fields.URLField(
        verbose_name="embed URL",
        help_text="Si vous souhaitez ajouter une url d'iframe à la place d'un 'Metabase ID', "
        "vous devez de mettre 0 dans le 'Metabase ID' et ajouter une url ci-dessus",
        null=True,
        blank=True,
    )
    description = models.fields.TextField(null=True, blank=True)
    tally_popup_id = models.fields.CharField(
        verbose_name="tally popup ID", null=True, blank=True, validators=[MaxLengthValidator(10)]
    )
    tally_embed_id = models.fields.CharField(
        verbose_name="tally embed ID", null=True, blank=True, validators=[MaxLengthValidator(10)]
    )
    active = models.fields.BooleanField(verbose_name="actif", default=True)
    new = models.fields.BooleanField(verbose_name="nouveau", default=False)

    def __str__(self):
        return f"{self.title}"

pilotage/users/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models


class UserGroup(AbstractUser):
    EDITOR = "EDITOR"
    SUBSCRIBER = "SUBSCRIBER"

    ROLE_CHOICES = (
        (EDITOR, "Éditeur"),
        (SUBSCRIBER, "Abonné"),
    )
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name="rôle")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.role == self.EDITOR:
            group = Group.objects.get(name="editors")
            group.user_set.add(self)
        elif self.role == self.SUBSCRIBER:
            group = Group.objects.get(name="subscribers")
            group.user_set.add(self)

pilotage/itoutils/forms.py
import string


class EmptyPlaceholderFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["placeholder"] = ""


class LetteredLabelFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for idx, field in enumerate(self.fields.values()):
            field.label = f"{string.ascii_lowercase[idx]}. {field.label}"

pilotage/api/views.py
import copy

from django.conf import settings
from django.db.models.enums import TextChoices
from django.http import (
    JsonResponse,
)

from pilotage.itoutils import metabase
from pilotage.itoutils.departments import DEPARTMENTS


class DataSetName(TextChoices):
    # API V0
    DI_SERVICES_V0 = "di_services", "data·inclusion - Services"
    DI_STRUCTURES_V0 = "di_structures", "data·inclusion - Structures"
    # API V1
    DI_SERVICES_V1 = "di_services_v1", "data·inclusion - Services"
    DI_STRUCTURES_V1 = "di_structures_v1", "data·inclusion - Structures"


QUERIES = {
    # API V0
    DataSetName.DI_SERVICES_V0: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2052,
            "fields": [
                ["field", 59639, {"base-type": "type/Text"}],  # ID
                ["field", 59644, {"base-type": "type/Text"}],  # Structure ID
                ["field", 59647, {"base-type": "type/Text"}],  # Source
                ["field", 59614, {"base-type": "type/Text"}],  # Nom
                ["field", 59643, {"base-type": "type/*"}],  # Thematiques
                ["field", 59627, {"base-type": "type/*"}],  # Frais
                ["field", 59636, {"base-type": "type/*"}],  # Profils
                ["field", 59649, {"base-type": "type/Text"}],  # Commune
                ["field", 59623, {"base-type": "type/Text"}],  # Code Postal
                ["field", 59654, {"base-type": "type/Text"}],  # Code Insee
                ["field", 59615, {"base-type": "type/Text"}],  # Adresse
                ["field", 59629, {"base-type": "type/Float"}],  # Longitude
                ["field", 59651, {"base-type": "type/Float"}],  # Latitude
                ["field", 59624, {"base-type": "type/*"}],  # Modes Accueil
            ],
            "filter": [
                "starts-with",
                ["field", 59654, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
    DataSetName.DI_STRUCTURES_V0: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2051,
            "fields": [
                ["field", 59591, {"base-type": "type/Text"}],  # ID
                ["field", 59600, {"base-type": "type/Text"}],  # Nom
                ["field", 59608, {"base-type": "type/Text"}],  # Commune
                ["field", 59606, {"base-type": "type/Text"}],  # Code Postal
                ["field", 59588, {"base-type": "type/Text"}],  # Code Insee
                ["field", 59605, {"base-type": "type/Text"}],  # Adresse
                ["field", 59594, {"base-type": "type/Float"}],  # Longitude
                ["field", 59599, {"base-type": "type/Float"}],  # Latitude
                ["field", 59590, {"base-type": "type/Text"}],  # Typologie
            ],
            "filter": [
                "starts-with",
                ["field", 59588, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
    # API V1
    DataSetName.DI_SERVICES_V1: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2169,
            "fields": [
                ["field", 62677, {"base-type": "type/Text"}],  # Source
                ["field", 62706, {"base-type": "type/Text"}],  # Structure ID
                ["field", 62694, {"base-type": "type/Text"}],  # ID
                ["field", 62685, {"base-type": "type/Text"}],  # Nom
                ["field", 62704, {"base-type": "type/*"}],  # Thematiques
                ["field", 62692, {"base-type": "type/Text"}],  # Frais
                ["field", 62710, {"base-type": "type/*"}],  # Publics
                ["field", 62700, {"base-type": "type/Text"}],  # Commune
                ["field", 62696, {"base-type": "type/Text"}],  # Code Postal
                ["field", 62686, {"base-type": "type/Text"}],  # Code Insee
                ["field", 62683, {"base-type": "type/Text"}],  # Adresse
                ["field", 62681, {"base-type": "type/Float"}],  # Longitude
                ["field", 62699, {"base-type": "type/Float"}],  # Latitude
                ["field", 62682, {"base-type": "type/*"}],  # Modes accueil
            ],
            "filter": [
                "starts-with",
                ["field", 62686, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
    DataSetName.DI_STRUCTURES_V1: {
        "database": 2,
        "type": "query",
        "query": {
            "source-table": 2170,
            "fields": [
                ["field", 62728, {"base-type": "type/Text"}],  # Source
                ["field", 62727, {"base-type": "type/Text"}],  # ID
                ["field", 62721, {"base-type": "type/Text"}],  # Nom
                ["field", 62716, {"base-type": "type/Text"}],  # Commune
                ["field", 62730, {"base-type": "type/Text"}],  # Code Postal
                ["field", 62719, {"base-type": "type/Text"}],  # Code Insee
                ["field", 62718, {"base-type": "type/Text"}],  # Adresse
                ["field", 62711, {"base-type": "type/Float"}],  # Longitude
                ["field", 62715, {"base-type": "type/Float"}],  # Latitude
                ["field", 62717, {"base-type": "type/*"}],  # Reseaux Porteurs
            ],
            "filter": [
                "starts-with",
                ["field", 62719, {"base-type": "type/Text"}],
                "000",  # Default to no-matchs
                {"case-sensitive": False},
            ],
        },
    },
}


def dataset(request, name):
    if name not in DataSetName:
        return JsonResponse({"error": "Dataset doesn't exists"}, status=404)

    # TODO: Use a query-builder like function to avoid a global and copying the query
    query = copy.deepcopy(QUERIES[DataSetName(name)])
    if department := request.GET.get("department"):
        if department not in DEPARTMENTS:
            return JsonResponse({"error": "Department doesn't exists"}, status=400)
        query["query"]["filter"][2] = department
    else:
        return JsonResponse({"error": "Department is a required query parameter"}, status=400)

    return JsonResponse(
        metabase.Client(settings.METABASE_BASE_URL).fetch_dataset_results(query),
        safe=False,  # Metabase return a list
    )

pilotage/dashboards/views.py
from django.shortcuts import get_object_or_404, render

from pilotage.dashboards.models import Dashboard


def tableaux_de_bord_publics(request):
    dashboards = (
        Dashboard.objects.filter(active=True)
        .select_related("category")
        .order_by("category__display_order", "-category__pk", "-pk")
    )
    return render(
        request,
        "dashboards/tableaux_de_bord_publics.html",
        context={"dashboards": dashboards},
    )


def tableau_de_bord_public(request, slug):
    dashboard = get_object_or_404(Dashboard, slug=slug)
    return render(
        request,
        "dashboards/tableau_de_bord_public.html",
        context={
            "dashboard": dashboard,
            "slug": slug,
            # Parameters for "partials/footer-scripts.html"
            "hasIframeResizer": not dashboard.embed_url,
            "hasIframeResizerFromOther": dashboard.embed_url,
            "hasTallyEmbed": dashboard.tally_embed_id,
            "hasTallyPopup": dashboard.tally_popup_id,
        },
    )

pilotage/pilotage/views.py
from django.shortcuts import render


def home(request):
    return render(request, "pilotage/home.html")


def stats(request):
    return render(request, "pilotage/statistiques.html")


def accessibilite(request):
    return render(request, "pilotage/accessibilite.html")


def politique_de_confidentialite(request):
    return render(request, "pilotage/politique_de_confidentialite.html")


def inscription_lettre_information(request):
    return render(request, "pilotage/inscription_lettre_information.html")


def mentions_legales(request):
    return render(request, "pilotage/mentions_legales.html")


def tableaux_de_bord_prives(request):
    return render(request, "pilotage/tableaux_de_bord_prives.html")

pilotage/users/views.py
from django.shortcuts import render

# Create your views here.

pilotage/templates/partials/footer.html
{% load static %}
{% load i18n %}
{% load theme_inclusion %}

<footer role="contentinfo" id="footer">
    <section class="s-footer-quick">
        <div class="s-footer-quick__container container">
            <div class="s-footer-quick__row row">
                <div class="s-footer-quick__col col-12 col-md-6 col-lg-auto">
                    <strong>Accès rapides</strong>
                    <ul>
                        <li>
                            <a href="{% url 'pilotage:home' %}">Accueil</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboards:tableaux_de_bord_publics' %}">Statistiques publiques</a>
                        </li>
                        <li>
                            <a href="{% url 'pilotage:tableaux_de_bord_prives' %}">Statistiques de mon organisation</a>
                        </li>
                        <li>
                            <a href="{% url 'pilotage:inscription_lettre_information' %}">Infolettre</a>
                        </li>
                    </ul>
                </div>
                <div class="s-footer-quick__col col-12 col-md-6 col-lg-auto">
                    <strong>Ressources</strong>
                    <ul>
                        <li>
                            <a href="{{ HELP_CENTER_BASE_URL }}/hc/fr/categories/16881943905297--Actualités-et-journal-des-évolutions-techniques" target="_blank" aria-label="Nouveautés (lien externe)">Nouveautés</a>
                        </li>
                        <li>
                            <a href="https://youtube.com/playlist?list=PLbjxvanoh-KbY_ku7d_MbIhDLgLWBxDTp&feature=shared" target="_blank" aria-label="Tutoriels et replays (lien externe)">Tutoriels et replays</a>
                        </li>
                        <li>
                            <a href="{{ HELP_CENTER_BASE_URL }}/hc/fr/categories/16881947647889--Webinaires-supports-et-replays" target="_blank" aria-label="Webinaires (lien externe)">Webinaires</a>
                        </li>
                        <li>
                            <a href="{{ GIP_SITE_BASE_URL }}/kits-de-communication/pilotage-de-linclusion/" target="_blank" aria-label="Kit de communication (lien externe)">Kit de communication</a>
                        </li>
                    </ul>
                </div>
                <div class="s-footer-quick__col col-12 col-lg-auto">
                    <strong>Réseaux sociaux</strong>
                    <ul>
                        <li>
                            <a href="https://www.linkedin.com/company/inclusion-gouv/" target="_blank" aria-label="La plateforme de l'inclusion sur sur Linkedin (lien externe)"><i class="ri-linkedin-box-fill text-dark" aria-hidden="true"></i> LinkedIn</a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/communaute.inclusion.gouv/" target="_blank" aria-label="La communaute de l'inclusion sur Facebook (lien externe)"><i class="ri-facebook-box-fill text-dark" aria-hidden="true"></i> Facebook</a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/@LaPlateformedelinclusion/videos" target="_blank" aria-label="La plateforme de l'inclusion sur Youtube (lien externe)"><i class="ri-youtube-fill text-dark" aria-hidden="true"></i> Youtube</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="s-footer-gip">
        <div class="s-footer-gip__container container">
            <div class="s-footer-gip__row row">
                <div class="s-footer-gip__col s-footer-gip__col--logo col-12 col-md-6 col-lg-auto">
                    <a href="{{ GIP_SITE_BASE_URL }}/" target="_blank" aria-label="Découvrez les services de la plateforme de l'inclusion (lien externe)">
                        <img src="{% static_theme_images 'logo-plateforme-inclusion.svg' %}" height="80" alt="Logo de plateforme de l'inclusion">
                    </a>
                </div>
                <div class="s-footer-gip__col col-12 col-md-6 col-lg">
                    <p class="mb-1">
                        <strong>Ce service fait partie de la Plateforme de l’inclusion</strong>
                    </p>
                    <p class="m-0">
                        Découvrez les outils qui portent l'inclusion au
                        <br class="d-none d-md-inline">
                        coeur de leur service. A chaque service, son objectif.
                        <br>
                        <a href="{{ GIP_SITE_BASE_URL }}/" target="_blank" class="has-external-link" aria-label="Découvrez les services de la plateforme de l'inclusion (lien externe)">Découvrez nos services</a>
                    </p>
                </div>
                <div class="s-footer-gip__col s-footer-gip__col--links col-12 col-lg-auto">
                    <ul>
                        <li>
                            <a href="https://beta.gouv.fr/" target="_blank" aria-label="Incubateur de services publics numériques — beta.gouv.fr (lien externe)">beta.gouv.fr</a>
                        </li>
                        <li>
                            <a href="https://www.data.gouv.fr/fr/" target="_blank" aria-label="Data.gouv.fr (lien externe)">data.gouv.fr</a>
                        </li>
                        <li>
                            <a href="https://api.gouv.fr/" target="_blank" aria-label="Simplifiez le partage et la circulation des données administratives grace à api.gouv.fr (lien externe)">api.gouv.fr</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="s-footer-legal">
        <div class="s-footer-legal__container container">
            <div class="s-footer-legal__row row">
                <div class="s-footer-legal__col col-12">
                    <ul>
                        <li>
                            <a href="{% url 'pilotage:mentions_legales' %}">Mentions légales</a>
                        </li>
                        <li>
                            <a href="{% url 'pilotage:politique_de_confidentialite' %}">Politique de confidentialité</a>
                        </li>
                        <li>
                            <a href="{% url 'pilotage:accessibilite' %}">Accessibilité : partiellement conforme</a>
                        </li>
                        <li>
                            <a href="{% url 'pilotage:statistiques' %}">Statistiques</a>
                        </li>
                    </ul>
                    <p>
                        Sauf mention contraire, tous les contenus de ce site sont sous licence <a href="https://github.com/etalab/licence-ouverte/blob/master/LO.md" target="_blank" aria-label="Licence ouverte Etalab (lien externe)">etalab-2.0</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
</footer>

pilotage/templates/partials/home_section_accompagne.html
{% load static %}

<section class="s-section mt-md-0 mb-md-7">
    <div class="s-section__container container container-max-lg">
        <div class="row mb-1 mb-md-3">
            <div class="col-12">
                <h2>Le pilotage vous accompagne</h2>
                <p>Vous travaillez dans une administration, service de l'Etat, une structure inclusive, un conseil départemental ? Vous souhaitez avoir des connaissances et des apprentissages sur les politiques publiques d'inclusion ? Le pilotage vous accompagne.</p>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-2 mt-3">
            <div class="col mb-3 mb-md-5">
                <div class="card h-100 text-center has-one-link-inside">
                    <div class="card-header pt-md-4 ps--md-4 pe-md-4">
                        <q>Combien de candidatures j'ai reçues ou orientée ? Quels sont leurs résultats ?</q>
                    </div>
                    <div class="card-body pb-0">
                        <img src="{% static 'images/pilotage/home/accompagne-01.png' %}" height="120" alt="">
                        <h3 class="mt-3 mb-0">
                            Simplifier le reporting et le bilan
                            <br class="d-none d-lg-inline">
                            de l'activité
                        </h3>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'pilotage:tableaux_de_bord_prives' %}" class="btn btn-link stretched-link" data-matomo-category="statistiques" data-matomo-action="click" data-matomo-option="simplifier">Accéder à mes statistiques</a>
                    </div>
                </div>
            </div>
            <div class="col mb-3 mb-md-5">
                <div class="card h-100 text-center has-one-link-inside">
                    <div class="card-header pt-md-4 ps--md-4 pe-md-4">
                        <q>
                            J’ai besoin de données pour préparer
                            <br class="d-none d-lg-inline">
                            mon CDIAE ?
                        </q>
                    </div>
                    <div class="card-body pb-0">
                        <img src="{% static 'images/pilotage/home/accompagne-02.png' %}" height="120" alt="">
                        <h3 class="mt-3 mb-0">Enrichir les instances locales de pilotage (dialogue de gestion, CTA, CTS, CDIAE…)</h3>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'pilotage:tableaux_de_bord_prives' %}" class="btn btn-link stretched-link" data-matomo-category="statistiques" data-matomo-action="click" data-matomo-option="enrichir">Accéder à mes statistiques</a>
                    </div>
                </div>
            </div>
            <div class="col mb-3 mb-md-5">
                <div class="card h-100 text-center has-one-link-inside">
                    <div class="card-header pt-md-4 ps--md-4 pe-md-4">
                        <q>Pourquoi les SIAE ont du mal à recruter, alors que les prescripteurs prescrivent bien ?</q>
                    </div>
                    <div class="card-body pb-0">
                        <img src="{% static 'images/pilotage/home/accompagne-03.png' %}" height="120" alt="">
                        <h3 class="mt-3 mb-0">Objectiver les situations et les échanges avec les partenaires</h3>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'pilotage:tableaux_de_bord_prives' %}" class="btn btn-link stretched-link" data-matomo-category="statistiques" data-matomo-action="click" data-matomo-option="objectiver">Accéder à mes statistiques</a>
                    </div>
                </div>
            </div>
            <div class="col mb-3 mb-md-5">
                <div class="card h-100 text-center has-one-link-inside">
                    <div class="card-header pt-md-4 ps--md-4 pe-md-4">
                        <q>Quelle est la situation sur mon territoire ? Les prescripteurs sont-ils mobilisés sur l'IAE ?</q>
                    </div>
                    <div class="card-body pb-0">
                        <img src="{% static 'images/pilotage/home/accompagne-04.png' %}" height="120" alt="">
                        <h3 class="mt-3 mb-0">Faciliter la réalisation et le suivi des plans d’actions</h3>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'pilotage:tableaux_de_bord_prives' %}" class="btn btn-link stretched-link" data-matomo-category="statistiques" data-matomo-action="click" data-matomo-option="faciliter">Accéder à mes statistiques</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

pilotage/templates/partials/home_section_apercu.html
<section class="s-section mt-md-0 mb-md-7">
    <div class="s-section__container container container-max-lg">
        <div class="row mb-1 mb-md-3">
            <div class="col-12">
                <h2 class="mb-0">Aperçu des connaissances apportées par les tableaux de bord</h2>
                <p class="fs-sm mb-3">Dernière mise à jour des données : 17 mars 2024</p>
            </div>
        </div>
        <div class="s-section__row row">
            <div class="col-12">
                <div class="d-flex flex-column flex-lg-row gap-2 p-3 p-md-4 bg-light rounded-3">
                    <div class="d-flex flex-column w-100">
                        <div class="flex-grow-1">
                            <p class="mb-0 mb-lg-3">
                                <i class="ri-arrow-down-line ri-2x text-pilotage" aria-hidden="true"></i>
                                <span class="h1">22%</span>
                            </p>
                            <p>c’est le taux de candidatures acceptées en 2025 par les SIAE</p>
                        </div>
                        <div>
                            <a href="{{ request.build_absolute_uri }}tableaux-de-bord/bilan-candidatures-iae/"
                               target="_blank"
                               aria-label="Consulter les données sur les candidatures acceptées"
                               class="btn btn-link ps-0 has-external-link">Consulter ces données</a>
                        </div>
                    </div>
                    <div class="d-flex flex-column w-100">
                        <div class="flex-grow-1">
                            <p class="mb-0 mb-lg-3">
                                <i class="ri-arrow-up-line ri-2x text-pilotage" aria-hidden="true"></i>
                                <span class="h1">686 724</span>
                            </p>
                            <p>c’est le nombre de candidatures orientées en 2025 vers les SIAE</p>
                        </div>
                        <div>
                            <a href="{{ request.build_absolute_uri }}tableaux-de-bord/bilan-candidatures-iae/"
                               target="_blank"
                               aria-label="Consulter les données sur les candidatures orientées"
                               class="btn btn-link ps-0 has-external-link">Consulter ces données</a>
                        </div>
                    </div>
                    <div class="d-flex flex-column w-100">
                        <div class="flex-grow-1">
                            <p class="mb-0 mb-lg-3">
                                <span class="h1">112 378</span>
                            </p>
                            <p>C'est le nombre de candidats à l'IAE sans candidature acceptée au 17&nbsp;mars&nbsp;2025.</p>
                        </div>
                        <div>
                            <a href="{{ request.build_absolute_uri }}tableaux-de-bord/bilan-candidatures-iae/"
                               target="_blank"
                               aria-label="Consulter les données sur les candidats à l'IAE sans candidatures acceptées"
                               class="btn btn-link ps-0 has-external-link">Consulter ces données</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

pilotage/templates/partials/home_section_comment.html
{% load static %}

<section class="s-section mt-md-0 mb-md-7">
    <div class="s-section__container container container-max-lg">
        <div class="row mb-1 mb-md-3">
            <div class="col-12">
                <h2>Comment j’accède aux données ?</h2>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 mt-3">
            <div class="col mb-3 mb-md-5">
                <div class="card h-100">
                    <div class="card-header">
                        <span class="d-block h2 text-pilotage">1</span>
                        <p>Je choisis le tableau de bord qui m’intéresse</p>
                    </div>
                    <div class="card-body">
                        <img src="{% static 'images/pilotage/home/comment-01.jpg' %}" class="img-fluid img-fitcover" alt="">
                    </div>
                </div>
            </div>
            <div class="col mb-3 mb-md-5">
                <div class="card h-100">
                    <div class="card-header">
                        <span class="d-block h2 text-pilotage">2</span>
                        <p>Je filtre les données pour affiner ma recherche</p>
                    </div>
                    <div class="card-body">
                        <img src="{% static 'images/pilotage/home/comment-02.jpg' %}" class="img-fluid img-fitcover" alt="">
                    </div>
                </div>
            </div>
            <div class="col mb-3 mb-md-5">
                <div class="card h-100">
                    <div class="card-header">
                        <span class="d-block h2 text-pilotage">3</span>
                        <p>Je consulte les chiffres et les graphiques que je peux aussi exporter</p>
                    </div>
                    <div class="card-body">
                        <img src="{% static 'images/pilotage/home/comment-03.jpg' %}" class="img-fluid img-fitcover" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>