config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from pilotage.api import urls as api_urls
from pilotage.dashboards import urls as dashboards_urls
from pilotage.pilotage import urls as pilotage_urls
from pilotage.surveys import urls as surveys_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(api_urls)),
    path("survey/", include(surveys_urls)),
    path("", include(pilotage_urls)),
    path("", include(dashboards_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pilotage/api/urls.py
from django.urls import path

from pilotage.api import views


app_name = "api"
urlpatterns = [
    path("dataset/<slug:name>", views.dataset, name="dataset"),
]

pilotage/pilotage/urls.py
from django.urls import include, path

from pilotage.pilotage import views


app_name = "pilotage"
urlpatterns = [
    path("", views.home, name="home"),
    path("dashboards/", include("pilotage.dashboards.urls")),
    path("stats/", views.stats, name="statistiques"),
    path("accessibilite/", views.accessibilite, name="accessibilite"),
    path("mentions-legales/", views.mentions_legales, name="mentions_legales"),
    path(
        "politique-de-confidentialite/",
        views.politique_de_confidentialite,
        name="politique_de_confidentialite",
    ),
    path(
        "inscription-lettre-information/",
        views.inscription_lettre_information,
        name="inscription_lettre_information",
    ),
    path(
        "tableaux-de-bord-prives/",
        views.tableaux_de_bord_prives,
        name="tableaux_de_bord_prives",
    ),
]

pilotage/surveys/urls.py
from django.urls import path

from pilotage.surveys import views


app_name = "surveys"
urlpatterns = [
    path("<slug:survey_name>/", views.start, name="start"),
    path("<slug:survey_name>/<uuid:answer_uid>/<str:step>", views.tunnel, name="tunnel"),
]

pilotage/dashboards/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name = "catégorie"
        verbose_name_plural = "catégories"

    title = models.fields.CharField(verbose_name="titre", validators=[MaxLengthValidator(100)])
    display_order = models.fields.PositiveSmallIntegerField(verbose_name="ordre d'affichage", blank=True, default=0)

    def __str__(self):
        return f"{self.title}"


class Dashboard(models.Model):
    class Meta:
        verbose_name = "tableau de bord"
        verbose_name_plural = "tableaux de bord"

    title = models.fields.CharField(verbose_name="titre", validators=[MaxLengthValidator(150)])
    baseline = models.fields.CharField(validators=[MaxLengthValidator(250)])
    slug = models.fields.SlugField(unique=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.DO_NOTHING,
        verbose_name="catégorie",
    )
    metabase_db_id = models.fields.IntegerField(verbose_name="metabase ID")
    embed_url = models.fields.URLField(
        verbose_name="embed URL",
        help_text="Si vous souhaitez ajouter une url d'iframe à la place d'un 'Metabase ID', "
        "vous devez de mettre 0 dans le 'Metabase ID' et ajouter une url ci-dessus",
        null=True,
        blank=True,
    )
    description = models.fields.TextField(null=True, blank=True)
    tally_popup_id = models.fields.CharField(
        verbose_name="tally popup ID", null=True, blank=True, validators=[MaxLengthValidator(10)]
    )
    tally_embed_id = models.fields.CharField(
        verbose_name="tally embed ID", null=True, blank=True, validators=[MaxLengthValidator(10)]
    )
    active = models.fields.BooleanField(verbose_name="actif", default=True)
    new = models.fields.BooleanField(verbose_name="nouveau", default=False)

    def __str__(self):
        return f"{self.title}"

pilotage/surveys/models.py
# FIXME: Remove the noqa once the verbose_name are confirmed
# ruff: noqa: E501

import uuid_utils
from django.contrib.postgres.fields import ArrayField, DateTimeRangeField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import TextChoices
from django.utils import timezone
from django.utils.text import slugify

from pilotage.itoutils.departments import DEPARTMENTS
from pilotage.itoutils.validators import validate_finess, validate_siret


def _uuid7():
    # TODO: Replace by the stdlib function when moving to Python 3.14.
    return str(uuid_utils.uuid7())


class SurveyKind(models.TextChoices):
    ESAT = "ESAT", "ESAT"


class SurveyQuerySet(models.QuerySet):
    def open(self):
        return self.filter(opening_period__contains=timezone.now())


class Survey(models.Model):
    kind = models.CharField(verbose_name="type", choices=SurveyKind.choices)
    vintage = models.CharField(verbose_name="millésime")
    name = models.SlugField(verbose_name="nom", unique=True, editable=False)
    opening_period = DateTimeRangeField(verbose_name="période d'ouverture")

    introduction = models.fields.TextField(null=True, blank=True)
    conclusion = models.fields.TextField(null=True, blank=True)

    created_at = models.DateTimeField(verbose_name="créé le", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="mis à jour le", auto_now=True)

    objects = SurveyQuerySet.as_manager()

    class Meta:
        verbose_name = "enquête"

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        self.name = self.name or slugify(f"{self.kind} {self.vintage}")
        super().save(**kwargs)

    @property
    def is_open(self):
        return timezone.now() in self.opening_period


class Answer(models.Model):
    uid = models.UUIDField(primary_key=True, default=_uuid7, editable=False)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name="answers", verbose_name="enquête")

    created_at = models.DateTimeField(verbose_name="créé le", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="mis à jour le", auto_now=True)

    class Meta:
        verbose_name = "réponse"

    def __str__(self):
        return str(self.uid)


DO_NOT_KNOW_VALUE = "DO_NOT_KNOW"
DO_NOT_KNOW_CHOICE = (DO_NOT_KNOW_VALUE, "Je ne sais pas")

NO_CHOICE = ("NO", "Non")


class BudgetFunding(TextChoices):
    BPAS = "BPAS", "Par votre budget de fonctionnement (BPAS)"
    BAPC = "BAPC", "Par votre budget annexe de production et de commercialisation (BAPC)"


class BudgetState(TextChoices):
    SURPLUS = "SURPLUS", "excédentaire"
    BALANCE = "BALANCE", "à l'équilibre"
    DEFICIT = "DEFICIT", "déficitaire"
    DO_NOT_KNOW = DO_NOT_KNOW_VALUE, "Je ne sais pas"


class BudgetRange(TextChoices):
    LESS_THAN_100K = "LESS_THAN_100K", "Moins de 100 k€"
    RANGE_100K_500K = "RANGE_100K_500K", "100 k€ à 500k€"
    MORE_THAN_500K = "MORE_THAN_500K", "Plus de 500k€"
    DO_NOT_KNOW = DO_NOT_KNOW_VALUE, "Je ne sais pas"


class DocumentFALCList(TextChoices):
    CONTRACT = "CONTRACT", "Oui : contrat d'accompagnement par le travail"
    BOOKLET = "BOOKLET", "Oui : livret d'accueil"
    REGULATION = "REGULATION", "Oui : règlement de fonctionnement"
    NO = NO_CHOICE


class SupportThemes(TextChoices):
    WORKSHOP_JOB_SEARCH = "WORKSHOP_JOB_SEARCH", "Atelier d'accompagnement à la recherche d'emplois"
    WORKSHOP_WELLBEING = "WORKSHOP_WELLBEING", "Ateliers de prévention santé / bien-être au travail"
    PROFESSIONAL_SUPPORT = "PROFESSIONAL_SUPPORT", "Soutien professionnel"
    CPF_OPENED = "CPF_OPENED", "Ouverture du Compte Professionnel de Formation"
    COMPANY_TOUR = "COMPANY_TOUR", "Visites dans les entreprises"
    COMPANY_PREMISES_MORNING_TOUR = "COMPANY_PREMISES_MORNING_TOUR", "Matinées entreprises dans les locaux"


class SkillsValidationType(TextChoices):
    RAE = "RAE", "Reconnaissance des acquis de l'expérience (RAE)"
    RSFP = "RSFP", "Reconnaissance des savoir-faire professinnels (RSFP)"
    VAE = "VAE", "Validation des acquis de l'expérience (VAE)"
    AFEST = "AFEST", "Action de formation en situation de travail (AFEST)"
    OTHER = "OTHER", "Autres actions"
    NONE = "NONE", "Aucune"


class AfterSkillsValidation(TextChoices):
    NO_CHANGES = "NO_CHANGES", "Maintien sur l'activité professionnelle initiale au sein de l'ESAT"
    OTHER_ACTIVITY = "OTHER_ACTIVITY", "Accès à d'autres activités professionnelles au sein de l'ESAT"
    OTHER_ESAT = "OTHER_ESAT", "Changement d'ESAT"
    ESRP = "ESRP", "Accès à une formation via un établissement ou service de réadaptation professionnelle (ESRP)"
    TRAINING_COURSE = "TRAINING_COURSE", "Accès à une formation via un organisme de formation"
    PARTIAL_TIME_WORK = "PARTIAL_TIME_WORK", "Accès à un emploi via le temps partagé"
    LEFT = "LEFT", "Sortie de l'ESAT pour accéder à un emploi en milieu ordinaire ou adapté"


class RetirementPreparationActions(TextChoices):
    ADMINISTRATIVE_ASSISTANCE = (
        "ADMINISTRATIVE_ASSISTANCE",
        "Accompagnement administratif (rendez-vous avec la CARSAT, aide à la préparation du dossier, informations sur les droits, etc.)",
    )
    UAAT = "UAAT", "Inscription dans la démarche Un Avenir Après le Travail"
    MEETING_SCHEDULED = (
        "MEETING_SCHEDULED",
        "Organisation d'un RDV avec un professionnel compétent sur le sujet (Assistante sociale, RH, Directeur/-trice, etc.)",
    )
    PERSONAL_PLAN = "PERSONAL_PLAN", "Inscription dans le projet de la personne"
    CAF = "CAF", "Simulation de ressources auprès des services de la CAF"
    WORKING_HOURS_REDUCTION_AND_ORGANISATION = (
        "WORKING_HOURS_REDUCTION_AND_ORGANISATION",
        "Aménagement / réduction du temps de travail",
    )
    PSYCHOLOGICAL_AND_SOCIAL_ASSISTANCE = (
        "PSYCHOLOGICAL_AND_SOCIAL_ASSISTANCE",
        "Actions de transition psychologique et sociale",
    )
    OTHER = "OTHER", "Autres"


class ESATAnswer(Answer):
    # ESATStep.ORGANIZATION
    esat_role = models.CharField(null=True, blank=True, verbose_name="quelle est votre fonction au sein de l'ESAT ?")
    esat_name = models.CharField(null=True, blank=True, verbose_name="quel est le nom de votre ESAT ?")
    esat_siret = models.CharField(
        null=True,
        blank=True,
        max_length=14,
        validators=[validate_siret],
        verbose_name="quel est le numéro SIRET de l'ESAT ?",
    )
    finess_num = models.CharField(
        null=True,
        blank=True,
        max_length=9,
        validators=[validate_finess],
        verbose_name="quel est le numéro FINESS de l'établissement principal ?",
    )
    managing_organization_name = models.CharField(
        null=True, blank=True, verbose_name="quel est votre organisme gestionnaire ?"
    )
    esat_status = models.CharField(
        null=True,
        blank=True,
        choices=[("PUBLIC", "Public"), ("NON_PROFIT", "Privé sans but lucratif")],
        verbose_name="quel est le statut de l'ESAT ?",
    )
    esat_dept = models.CharField(
        null=True,
        blank=True,
        choices=DEPARTMENTS.items(),
        verbose_name="quel est le département d'implantation de l'ESAT ?",
    )

    nb_places_allowed = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=1,
        max_digits=4,
        validators=[MinValueValidator(0)],
        verbose_name="au 31 décembre n-1, quel était l'agrément fixé par l'ARS pour l'ESAT en nombre de places autorisées ?",
    )
    nb_employee_worked = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=1,
        max_digits=4,
        validators=[MinValueValidator(0)],
        verbose_name="combien de salarié(e)s ou d'agents publics (ESAT publics) ont été employés dans l'ESAT ?",
        help_text="En équivalent temps plein (ETP), salariés ou agents publics encore en poste au 31/12/n-1 et ceux partis dans l'année",
    )

    # ESATStep.WORKERS_SUPPORTED
    nb_worker_acc = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="combien de travailleurs et travailleuses avez-vous accompagné ?",
        help_text="En nombre de travailleurs (effectif physique) en file active",
    )
    mean_worker_age = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=1,
        max_digits=3,
        validators=[MinValueValidator(0), MaxValueValidator(80)],
        verbose_name="au 31 décembre n-1, quel était l'âge moyen des travailleurs et travailleuses accompagnés ?",
        help_text="En nombre d'années",
    )
    mean_seniority = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=1,
        max_digits=3,
        validators=[MinValueValidator(0)],
        verbose_name="au 31 décembre n-1, quelle était l'ancienneté moyenne des travailleurs et travailleuses accompagnés ?",
        help_text="En nombre d'années",
    )
    nb_worker_half_time = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="parmi eux, combien de travailleurs et travailleuses étaient à temps partiel ?",
        help_text="En nombre de travailleurs (effectif physique) en file active",
    )

    # ESATStep.WORKERS_ENTRY
    nb_worker_previous_mot = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="quel était le nombre de travailleurs et travailleuses dans l'ESAT ayant occupé antérieurement à leur admission un emploi en milieu ordinaire (y compris entreprise adapté) ?",
        help_text="En nombre de travailleurs (effectif physique) parmi ceux admis en n-1",
    )
    nb_worker_new = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="quel était le nombre de travailleurs et travailleuses dans l'ESAT admis pour la première fois en milieu protégé de travail ?",

pilotage/users/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models


class UserGroup(AbstractUser):
    EDITOR = "EDITOR"
    SUBSCRIBER = "SUBSCRIBER"

    ROLE_CHOICES = (
        (EDITOR, "Éditeur"),
        (SUBSCRIBER, "Abonné"),
    )
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name="rôle")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.role == self.EDITOR:
            group = Group.objects.get(name="editors")
            group.user_set.add(self)
        elif self.role == self.SUBSCRIBER:
            group = Group.objects.get(name="subscribers")
            group.user_set.add(self)

pilotage/itoutils/forms.py
import string


class EmptyPlaceholderFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["placeholder"] = ""


class LetteredLabelFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for idx, field in enumerate(self.fields.values()):
            field.label = f"{string.ascii_lowercase[idx]}. {field.label}"

pilotage/dashboards/views.py
from django.shortcuts import get_object_or_404, render

from pilotage.dashboards.models import Dashboard


def tableaux_de_bord_publics(request):
    dashboards = (
        Dashboard.objects.filter(active=True)
        .select_related("category")
        .order_by("category__display_order", "-category__pk", "-pk")
    )
    return render(
        request,
        "dashboards/tableaux_de_bord_publics.html",
        context={"dashboards": dashboards},
    )


def tableau_de_bord_public(request, slug):
    dashboard = get_object_or_404(Dashboard, slug=slug)
    return render(
        request,
        "dashboards/tableau_de_bord_public.html",
        context={
            "dashboard": dashboard,
            "slug": slug,
            # Parameters for "partials/footer-scripts.html"
            "hasIframeResizer": not dashboard.embed_url,
            "hasIframeResizerFromOther": dashboard.embed_url,
            "hasTallyEmbed": dashboard.tally_embed_id,
            "hasTallyPopup": dashboard.tally_popup_id,
        },
    )

pilotage/pilotage/views.py
from django.shortcuts import render


def home(request):
    return render(request, "pilotage/home.html")


def stats(request):
    return render(request, "pilotage/statistiques.html")


def accessibilite(request):
    return render(request, "pilotage/accessibilite.html")


def politique_de_confidentialite(request):
    return render(request, "pilotage/politique_de_confidentialite.html")


def inscription_lettre_information(request):
    return render(request, "pilotage/inscription_lettre_information.html")


def mentions_legales(request):
    return render(request, "pilotage/mentions_legales.html")


def tableaux_de_bord_prives(request):
    return render(request, "pilotage/tableaux_de_bord_prives.html")

pilotage/users/views.py
from django.shortcuts import render

# Create your views here.

pilotage/templates/surveys/survey.html
{% extends "layouts/base.html" %}
{% load django_bootstrap5 %}
{% load markdown_extras %}
{% load surveys %}

{% block title %}Étude {{ survey.get_kind_display }} {{ survey.vintage }} - {{ block.super }}{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="c-breadcrumb" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'pilotage:home' %}">Accueil</a>
                            </li>
                            <li class="breadcrumb-item" aria-current="page">Étude {{ survey.get_kind_display }} {{ survey.vintage }}</li>
                            <li class="breadcrumb-item active" aria-current="page">{{ title|capfirst }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    <section class="s-title-01">
        <div class="s-title-01__container container">
            <div class="s-title-01__row row">
                <div class="s-title-01__col col-12 col-lg-12">
                    <h1>Étude {{ survey.get_kind_display }} {{ survey.vintage }}</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="s-section">
        <div class="s-section__container container">
            <div class="s-section__row row">
                <div class="s-section__col col-12 col-lg-8 order-last order-lg-first">
                    <div class="c-form mb-3 mb-md-4">
                        <h2>{{ title|capfirst }}</h2>
                        {% if not form %}
                            {{ content|default_if_none:"" | markdown | safe }}
                            <div class="form-group text-end">
                                {% if previous_step_url %}
                                    {% bootstrap_button "Retour" button_type="link" href=previous_step_url button_class="btn-outline-primary" %}
                                {% endif %}
                                {% if next_step_url %}
                                    {% bootstrap_button "Suivant" button_type="link" href=next_step_url %}
                                {% endif %}
                            </div>
                        {% elif form %}
                            <form method="post">

                                {% csrf_token %}

                                {% bootstrap_form_errors form type="all" %}

                                {% for field in form %}
                                    {% label_with_info field labels_information %}
                                    {% bootstrap_field field show_label="skip" %}
                                {% endfor %}

                                <div class="form-group text-end">
                                    {% if previous_step_url %}
                                        {% bootstrap_button "Précédent" button_type="submit" name="goto" value="previous" button_class="btn-outline-primary" %}
                                    {% endif %}
                                    {% bootstrap_button "Suivant" button_type="submit" %}
                                </div>
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div class="s-section__col col-12 col-lg-4 order-first order-lg-last">
                    <div class="c-box mb-3 mb-md-4">
                        <h2>Étapes du formulaire</h2>
                        <hr>
                        <ol>
                            {% for step, info in steps_info.items %}
                                <li>
                                    {% if current_step == step %}
                                        <b>{{ step.label|capfirst }}</b>
                                    {% else %}
                                        <a href="{% url "surveys:tunnel" survey_name=survey.name answer_uid=answer.uid step=step %}">{{ step.label|capfirst }}</a>
                                    {% endif %}
                                    - {{ info.filled }}/{{ info.total }}
                                </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}